### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by amatorecorrado** [devfviak/node-hls-server#3]
I found an error immediately with simple configuration:

const HLSServer = require('node-hls-server');
const server = new HLSServer(); 
server.run();

the error is:
/Users/---------->/live_server/node_modules/node-hls-server/requestHandler.js:24
        req.connection?.remoteAddress ||
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/------>/live_server/node_modules/node-hls-server/hlsServer.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

**Comment by advplyr** [comment]
Optional chaining in node >= 14

**Comment by pedrio-gh** [comment]
I will take a look at this error to make it compatible with older node versions.
